dependencies:
  - name: kms-cmake-utils
    version: ">= 1.5.0"
  - name: kms-core
    version: ">= 6.6.2"
  - name: kms-elements
    version: ">= 6.6.2"
  - name: kms-filters
    version: ">= 6.6.2"
